require("lazy").setup({
    -- themes
    "sainnhe/sonokai",
    "tiagovla/tokyodark.nvim",
    "projekt0n/github-nvim-theme",
    "joshdick/onedark.vim",
    { "catppuccin/nvim", name = "catppuccin" },
    "liuchengxu/space-vim-dark",
    "ahmedabdulrahman/aylin.vim",
    "rebelot/kanagawa.nvim",
    "NLKNguyen/papercolor-theme",
    "liuchengxu/space-vim-dark",
    "sainnhe/edge",
    "nyoom-engineering/oxocarbon.nvim",
    "Th3Whit3Wolf/one-nvim",
    "AlexvZyl/nordic.nvim",
    "lewis6991/gitsigns.nvim",

    -- basics
    "kyazdani42/nvim-web-devicons",
    "nvim-lua/plenary.nvim",
    "MunifTanjim/nui.nvim",
    "nvim-tree/nvim-tree.lua",
    "akinsho/bufferline.nvim",
    "moll/vim-bbye",

    -- language
    "neovim/nvim-lspconfig",
    "glepnir/lspsaga.nvim",
    "hrsh7th/cmp-nvim-lsp",
    "hrsh7th/cmp-buffer",
    "hrsh7th/cmp-path",
    "hrsh7th/cmp-cmdline",
    "hrsh7th/nvim-cmp",
    "L3MON4D3/LuaSnip",
    "nvim-treesitter/nvim-treesitter",
    "simrat39/rust-tools.nvim",
    "dnlhc/glance.nvim",
    "tamago324/nlsp-settings.nvim",
    "folke/trouble.nvim",
    "nvim-lualine/lualine.nvim",
    "akinsho/toggleterm.nvim",
    "BurntSushi/ripgrep",
    "nvim-telescope/telescope.nvim",
    "goolord/alpha-nvim",
    "petertriho/nvim-scrollbar",
})
